name: hijr_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  fsearch: ^2.0.0
  outline_search_bar: ^2.3.0
  rename: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/map.svg
    - assets/Icons/Alarm.svg
    - assets/Icons/Qibla.svg
    - assets/Icons/Prayer.svg
    - assets/Icons/Nothing.svg
    - assets/Icons/Home.svg
    - assets/Icons/Routines.svg
    - assets/Icons/Discover.svg
    - assets/Icons/Profile.svg
    - assets/Icons/Close.svg
    - assets/Icons/PeopleFix.svg
    - assets/Icons/Search.svg
    - assets/Icons/ProfileUser.svg

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/Fonts/Work_Sans/static/WorkSans-Regular.ttf
